param(
    [string] $PackageRoot = "",
    [string] $DriverPackageDir = "",
    [string] $SymbolsDir = "",
    [string] $OutputDir = "",
    [string] $CabName = "MonitorSplitterDriver-attestation.cab",
    [string] $PackageFolderName = "MonitorSplitterDriver",
    [switch] $SignCab,
    [string] $EvCertificateSubject = "",
    [string] $TimestampUrl = "http://timestamp.digicert.com",
    [string] $MakeCabExe = "",
    [string] $SignToolExe = "",
    [switch] $SelfTest
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-FullPath {
    param([Parameter(Mandatory=$true)][string] $Path)
    return [IO.Path]::GetFullPath($Path)
}

function Resolve-FirstExistingPath {
    param(
        [Parameter(Mandatory=$true)][string] $Name,
        [Parameter(Mandatory=$true)][string[]] $Candidates
    )

    foreach ($candidate in $Candidates) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
            return $candidate
        }
    }

    throw "$Name not found. Checked: $($Candidates -join '; ')"
}

function Resolve-ProgramFilesPath {
    param([switch] $X86)

    if ($X86) {
        $path = ${env:ProgramFiles(x86)}
        if ([string]::IsNullOrWhiteSpace($path)) {
            return "C:\Program Files (x86)"
        }
        return $path
    }

    if ([string]::IsNullOrWhiteSpace($env:ProgramFiles)) {
        return "C:\Program Files"
    }
    return $env:ProgramFiles
}

function Resolve-WindowsKitTool {
    param(
        [Parameter(Mandatory=$true)][string] $ToolName,
        [string] $Architecture = "x86",
        [string] $PreferredVersion = "10.0.26100.0"
    )

    $command = Get-Command $ToolName -ErrorAction SilentlyContinue
    if ($null -ne $command) {
        return $command.Source
    }

    $toolRoot = Join-Path (Join-Path (Resolve-ProgramFilesPath -X86) "Windows Kits\10") "bin"
    $candidates = New-Object System.Collections.Generic.List[string]
    $candidates.Add((Join-Path $toolRoot "$PreferredVersion\$Architecture\$ToolName"))
    if (Test-Path -LiteralPath $toolRoot -PathType Container) {
        Get-ChildItem -LiteralPath $toolRoot -Directory |
            Sort-Object Name -Descending |
            ForEach-Object { $candidates.Add((Join-Path $_.FullName "$Architecture\$ToolName")) }
    }

    Resolve-FirstExistingPath $ToolName @($candidates)
}

function Invoke-Checked {
    param(
        [Parameter(Mandatory=$true)][string] $FilePath,
        [Parameter(ValueFromRemainingArguments=$true)][string[]] $Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
    }
}

function Assert-RequiredDriverPackage {
    param([Parameter(Mandatory=$true)][string] $Path)

    foreach ($fileName in @("MonitorSplitterDriver.inf", "MonitorSplitterDriver.dll", "monitorsplitterdriver.cat")) {
        $filePath = Join-Path $Path $fileName
        if (-not (Test-Path -LiteralPath $filePath -PathType Leaf)) {
            throw "Driver package is incomplete; missing $filePath. Run scripts\package-driver.ps1 first."
        }
    }
}

function New-AttestationDdf {
    param(
        [Parameter(Mandatory=$true)][string] $Path,
        [Parameter(Mandatory=$true)][string] $CabinetName,
        [Parameter(Mandatory=$true)][string] $DestinationDir,
        [Parameter(Mandatory=$true)][string[]] $FileNames
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("; Generated by MonitorSplitter package-attestation-cab.ps1") | Out-Null
    $lines.Add(".OPTION EXPLICIT") | Out-Null
    $lines.Add(".Set CabinetFileCountThreshold=0") | Out-Null
    $lines.Add(".Set FolderFileCountThreshold=0") | Out-Null
    $lines.Add(".Set FolderSizeThreshold=0") | Out-Null
    $lines.Add(".Set MaxCabinetSize=0") | Out-Null
    $lines.Add(".Set MaxDiskFileCount=0") | Out-Null
    $lines.Add(".Set MaxDiskSize=0") | Out-Null
    $lines.Add(".Set CompressionType=MSZIP") | Out-Null
    $lines.Add(".Set Cabinet=on") | Out-Null
    $lines.Add(".Set Compress=on") | Out-Null
    $lines.Add(".Set CabinetNameTemplate=$CabinetName") | Out-Null
    $lines.Add(".Set DiskDirectoryTemplate=.") | Out-Null
    $lines.Add(".Set DestinationDir=$DestinationDir") | Out-Null
    foreach ($fileName in $FileNames) {
        $lines.Add($fileName) | Out-Null
    }

    Set-Content -LiteralPath $Path -Encoding ascii -Value $lines
}

function Get-CabFileList {
    param(
        [Parameter(Mandatory=$true)][string] $CabPath,
        [Parameter(Mandatory=$true)][string] $ExpandExe
    )

    $output = & $ExpandExe -D $CabPath
    if ($LASTEXITCODE -ne 0) {
        throw "Could not list CAB contents: $CabPath"
    }

    return @($output |
        ForEach-Object { [string] $_ } |
        Where-Object { $_ -match ":\s*[^\\/:]+\.[A-Za-z0-9]+$" } |
        ForEach-Object {
            if ($_ -match ":\s*([^\\/:]+\.[A-Za-z0-9]+)$") {
                $Matches[1]
            }
        })
}

function Assert-DdfLayout {
    param(
        [Parameter(Mandatory=$true)][string] $Path,
        [Parameter(Mandatory=$true)][string] $DestinationDir
    )

    $text = Get-Content -LiteralPath $Path -Raw
    if ($text -notmatch "(?im)^\.Set\s+DestinationDir=$([regex]::Escape($DestinationDir))\s*$") {
        throw "Attestation DDF does not place package files under the $DestinationDir subfolder."
    }
}

function Assert-CabFileList {
    param(
        [Parameter(Mandatory=$true)][string[]] $CabEntries,
        [Parameter(Mandatory=$true)][string[]] $ExpectedFiles
    )

    $missing = @($ExpectedFiles | Where-Object { $CabEntries -notcontains $_ })
    $extra = @($CabEntries | Where-Object { $ExpectedFiles -notcontains $_ })
    if ($missing.Count -gt 0 -or $extra.Count -gt 0) {
        throw "Attestation CAB file list mismatch. Missing=[$($missing -join ', ')] Extra=[$($extra -join ', ')]"
    }
}

function Invoke-SelfTest {
    $root = Join-Path ([IO.Path]::GetTempPath()) "MonitorSplitterAttestationSelfTest.$PID.$([Guid]::NewGuid().ToString('N'))"
    try {
        $driverDir = Join-Path $root "driver-package"
        $symbolDir = Join-Path $root "symbols"
        New-Item -ItemType Directory -Force -Path $driverDir, $symbolDir | Out-Null
        Set-Content -LiteralPath (Join-Path $driverDir "MonitorSplitterDriver.inf") -Encoding ascii -Value "[Version]"
        Set-Content -LiteralPath (Join-Path $driverDir "MonitorSplitterDriver.dll") -Encoding ascii -Value "dll"
        Set-Content -LiteralPath (Join-Path $driverDir "monitorsplitterdriver.cat") -Encoding ascii -Value "cat"
        Set-Content -LiteralPath (Join-Path $symbolDir "MonitorSplitterDriver.pdb") -Encoding ascii -Value "pdb"

        $global:LASTEXITCODE = 0
        & $PSCommandPath -PackageRoot $root -DriverPackageDir $driverDir -SymbolsDir $symbolDir -OutputDir (Join-Path $root "attestation") | Out-Null
        if (-not (Test-Path -LiteralPath (Join-Path $root "attestation\MonitorSplitterDriver-attestation.cab") -PathType Leaf)) {
            throw "self-test did not produce CAB"
        }

        Write-Host "Attestation CAB packaging self-test passed."
    }
    finally {
        if (Test-Path -LiteralPath $root) {
            Remove-Item -LiteralPath $root -Recurse -Force
        }
    }
}

if ($SelfTest) {
    Invoke-SelfTest
    return
}

if ([string]::IsNullOrWhiteSpace($PackageRoot)) {
    $PackageRoot = Join-Path $RepoRoot "out"
}
if ([string]::IsNullOrWhiteSpace($DriverPackageDir)) {
    $DriverPackageDir = Join-Path $PackageRoot "driver-package"
}
if ([string]::IsNullOrWhiteSpace($SymbolsDir)) {
    $SymbolsDir = Join-Path $PackageRoot "symbols"
}
if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $PackageRoot "attestation"
}
if ([string]::IsNullOrWhiteSpace($MakeCabExe)) {
    $MakeCabExe = Resolve-FirstExistingPath "makecab.exe" @((Get-Command makecab.exe -ErrorAction SilentlyContinue).Source, (Join-Path $env:SystemRoot "System32\makecab.exe"))
}

$PackageRoot = Resolve-FullPath $PackageRoot
$DriverPackageDir = Resolve-FullPath $DriverPackageDir
$SymbolsDir = Resolve-FullPath $SymbolsDir
$OutputDir = Resolve-FullPath $OutputDir
Assert-RequiredDriverPackage $DriverPackageDir

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$stagingRoot = Join-Path $OutputDir "staging"
$stagingPackageDir = Join-Path $stagingRoot $PackageFolderName
if (Test-Path -LiteralPath $stagingRoot) {
    Remove-Item -LiteralPath $stagingRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $stagingPackageDir | Out-Null

$attestationFiles = New-Object System.Collections.Generic.List[string]
foreach ($fileName in @("MonitorSplitterDriver.inf", "MonitorSplitterDriver.dll", "monitorsplitterdriver.cat")) {
    Copy-Item -LiteralPath (Join-Path $DriverPackageDir $fileName) -Destination (Join-Path $stagingPackageDir $fileName) -Force
    $attestationFiles.Add($fileName) | Out-Null
}

$pdbPath = Join-Path $SymbolsDir "MonitorSplitterDriver.pdb"
if (Test-Path -LiteralPath $pdbPath -PathType Leaf) {
    Copy-Item -LiteralPath $pdbPath -Destination (Join-Path $stagingPackageDir "MonitorSplitterDriver.pdb") -Force
    $attestationFiles.Add("MonitorSplitterDriver.pdb") | Out-Null
}
else {
    Write-Warning "Driver PDB was not found at $pdbPath. Microsoft recommends including the PDB for automated crash analysis."
}

$ddfPath = Join-Path $OutputDir "MonitorSplitterDriver-attestation.ddf"
New-AttestationDdf -Path $ddfPath -CabinetName $CabName -DestinationDir $PackageFolderName -FileNames @($attestationFiles)

Push-Location $stagingPackageDir
try {
    Invoke-Checked -FilePath $MakeCabExe -Arguments @("/f", $ddfPath)
    $generatedCab = Join-Path $stagingPackageDir $CabName
    if (-not (Test-Path -LiteralPath $generatedCab -PathType Leaf)) {
        throw "MakeCab completed but did not produce $generatedCab"
    }
    $cabPath = Join-Path $OutputDir $CabName
    Move-Item -LiteralPath $generatedCab -Destination $cabPath -Force
}
finally {
    Pop-Location
}

$expandExe = Resolve-FirstExistingPath "expand.exe" @((Get-Command expand.exe -ErrorAction SilentlyContinue).Source, (Join-Path $env:SystemRoot "System32\expand.exe"))
$entries = @(Get-CabFileList -CabPath $cabPath -ExpandExe $expandExe)
Assert-DdfLayout -Path $ddfPath -DestinationDir $PackageFolderName
Assert-CabFileList -CabEntries $entries -ExpectedFiles @($attestationFiles)

if ($SignCab) {
    if ([string]::IsNullOrWhiteSpace($EvCertificateSubject)) {
        throw "Pass -EvCertificateSubject when using -SignCab."
    }
    if ([string]::IsNullOrWhiteSpace($SignToolExe)) {
        $SignToolExe = Resolve-WindowsKitTool "signtool.exe" "x86"
    }
    Invoke-Checked -FilePath $SignToolExe -Arguments @(
        "sign",
        "/s", "MY",
        "/n", $EvCertificateSubject,
        "/fd", "sha256",
        "/tr", $TimestampUrl,
        "/td", "sha256",
        "/v",
        $cabPath)
}

[pscustomobject]@{
    ok = $true
    cabPath = $cabPath
    ddfPath = $ddfPath
    signed = [bool] $SignCab
    entries = $entries
} | ConvertTo-Json -Depth 4
